name: Build and Push Docker Image

on:
  push:
    branches:
      - dev_hung_be # Chạy khi có push lên nhánh main
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Chạy trên máy ảo Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Lấy code từ repo

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=hung2304/shtt-backend  # Thay bằng tên Docker image của bạn
          TAG=latest  # Hoặc dùng `$(date +%s)` để tạo tag timestamp
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/my-app my-app=hung2304/shtt-backend:$TAG
          kubectl rollout restart deployment/my-app
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
